name: flutter_phone_number_field
description: International phone number field
version: 0.0.1
repository: https://github.com/flutter-form-builder-ecosystem/form_builder_phone_field
homepage: https://github.com/flutter-form-builder-ecosystem


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.0.0
  country_code_picker: ^3.0.0
 

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
